src/app/navigation/navigation.component.html
=> Click logo to go home.

src/app/app.module.ts, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.css, src/app/new-goal-dialog/new-goal-dialog.component.html, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/rest.service.ts, src/express/manufacturing_activity_utils.js, src/express/manufacturing_goals_utils.js, src/express/manufacturing_line_utils.js, src/express/server.js
Can create new goals, with activities, using the New Goal Dialog. Goals don't show up on table yet.
=> New goals Dialog functional

package-lock.json, src/app/app.module.ts, src/app/enable-goals-dialog/enable-goals-dialog.component.css, src/app/enable-goals-dialog/enable-goals-dialog.component.html, src/app/enable-goals-dialog/enable-goals-dialog.component.spec.ts, src/app/enable-goals-dialog/enable-goals-dialog.component.ts, src/app/enable-goals-dialog/manufacturing-goals-tables-component.css, src/app/enable-goals-dialog/manufacturing-goals-tables-component.html, src/app/enable-goals-dialog/manufacturing-goals-tables-component.ts, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/manufacturing-schedule/manufacturing-schedule.component.html, src/app/manufacturing-schedule/manufacturing-schedule.component.ts, src/app/navigation/navigation.component.html, src/app/rest.service.ts, src/express/manufacturing_goals_utils.js, src/express/server.js
- Need to fix bug in getGoals, to get by enabled status, not by username
=> Enabling Goals Drag/Drop works

src/app/app.module.ts, src/app/enable-goals-dialog/enable-goals-dialog.component.html, src/app/enable-goals-dialog/enable-goals-dialog.component.ts, src/app/manufacturing-goals/manufacturing-goals.component.html, src/app/manufacturing-schedule/manufacturing-schedule.component.html, src/app/manufacturing-schedule/manufacturing-schedule.component.ts, src/app/modify-activity-dialog/modify-activity-dialog.component.html, src/app/modify-activity-dialog/modify-activity-dialog.component.spec.ts, src/app/modify-activity-dialog/modify-activity-dialog.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.html, src/app/rest.service.ts, src/express/manufacturing_activity_utils.js, src/express/server.js
=> Displays Enabled Manufacturing Goals and activities on schedule

src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/rest.service.ts
- doesn't get activities if there are none
=> Fixed manufacturing goals create bug

src/app/manufacturing-schedule/manufacturing-lines-table.component.ts, src/app/manufacturing-schedule/manufacturing-schedule-tables.component.ts, src/app/manufacturing-schedule/manufacturing-schedule.component.ts, src/app/rest.service.ts, src/express/server.js
- Can drag an activity from a manufacturing goal to a manufacturing line
=> Manufacturing schedule

src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.html, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/rest.service.ts, src/express/manufacturing_activity_utils.js, src/express/server.js
- Can modify manufacturing goals
=> Fixed modifying goals

src/app/manufacturing-goals/manufacturing-goals.component.html, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/manufacturing-schedule/manufacturing-lines-table.component.html, src/app/manufacturing-schedule/manufacturing-lines-table.component.ts, src/app/manufacturing-schedule/manufacturing-schedule-tables.component.html, src/app/manufacturing-schedule/manufacturing-schedule-tables.component.ts, src/app/manufacturing-schedule/manufacturing-schedule.component.ts, src/app/rest.service.ts
Displays dates in MM/DD/YYYY format, not weird javascript date format
=> Fixed date formatting

src/app/rest.service.ts, src/app/sku/sku.component.ts
For example, if a sku had been checked, the wrong one would be edited.
=> This pull request fixes a number of problems with modifying skus. 

src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.html, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/rest.service.ts, src/express/manufacturing_activity_utils.js, src/express/manufacturing_goals_utils.js, src/express/server.js
=> Activity fixes

src/app/delete-product-line-dialog/delete-product-line-dialog.component.ts, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/rest.service.ts
- Manufacturing goals are user-specific
- Rounded activity hours
- Removed debugging comments from delete product line
=> Manufacturing goal bug fixes.

src/app/manufacturing-calculator/manufacturing-calculator.component.css, src/app/manufacturing-calculator/manufacturing-calculator.component.html, src/app/manufacturing-calculator/manufacturing-calculator.component.ts, src/app/manufacturing-goals/manufacturing-goals.component.html, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/navigation/navigation.component.html, src/assets/baseline-info-24px.svg
- Made the manufacturing calculator a dialog of the manufacturing goals
- Fixed calculator math
=> Combined Goals and Calculator

src/app/ingredient-dependency-report/ingredient-dependency-report.component.ts, src/app/ingredient/ingredient.component.ts
- Renamed files, fixed ingredient dependency CSV formatting
=> Fixed ingredient + dependency csv exporting

src/app/manufacturing-goals/manufacturing-goals.component.html
- Renamed from Info to Calculator to make it easier to find
=> Renamed Manufacturing Calculator column

src/app/new-sku-dialog/new-sku-dialog.component.ts
- When creating a SKU, the sku gets added to the correct product line
=> Fixed create SKU bug

src/app/enable-goals-dialog/manufacturing-goals-tables-component.ts, src/app/manufacturing-goals/manufacturing-goals.component.html, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/rest.service.ts, src/assets/baseline-delete-24px.svg, src/assets/baseline-done-24px.svg, src/express/database.js, src/express/v2/manufacturing_goals_utils.js
- Last edit and owner fields added to table
- Business Managers can enable goals from this page
=> Manufacturing goals

src/app/activity-details/activity-details.component.ts, src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/rest.service.ts, src/app/restv2.service.ts, src/app/sales-projection/sales-projection.component.html, src/app/sales-projection/sales-projection.component.ts, src/express/v2/manufacturing_activity_utils.js, src/express/v2/manufacturing_goals_utils.js
- Can now save average sales projection as quantity for activity
=> Completed Sales Projection Tool

src/app/manufacturing-calculator/manufacturing-calculator.component.html, src/app/manufacturing-calculator/manufacturing-calculator.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.html, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/app/sales-projection/sales-projection.component.ts
- Automatically changes year to this year, no matter what year you select on the date picker, so the correct sales years can be chosen
=> Fixed some bugs with dates in Sales Projection Tool

src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/manufacturing-lines/manufacturing-lines.component.html, src/app/manufacturing-lines/manufacturing-lines.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.html
- Analysts can't edit or delete
=> Fixed RBAC for goals

src/app/manufacturing-goals/manufacturing-goals.component.ts, src/app/new-goal-dialog/new-goal-dialog.component.html, src/app/new-goal-dialog/new-goal-dialog.component.ts, src/express/v2/manufacturing_activity_utils.js
- Error matcher so you can't create a goal with the same name as another
- Added an "X" button to delete activities
=> Some fixes and improvements for manufacturing goals page

src/app/rest.service.ts, src/app/sku/sku.component.ts
- Deleting a SKU deletes all activities with that SKU, modifying goals with affected activities
=> Data Integrity for Activities
